sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
before_script:
  - cd themes
  - cd miho
  - npm install hexo-generator-json-content --save

branches:
  only:
    - main # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public